
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;



/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author shubham
 */
public class Admin extends javax.swing.JFrame {

    /**
     * Creates new form administrator
     */
    Connection conn=null;
    Login l;
    public Admin() {
        initComponents();
       l=new Login();
       try {
            Class.forName("com.mysql.jdbc.Driver");
            String user="root";
            String pass="sayan1994";
            String DB_URL = "jdbc:mysql://"+l.IP_ADD+"/rrts";
            conn = DriverManager.getConnection(DB_URL,user,pass);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(entercom.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(entercom.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        cid1 = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        mc7 = new javax.swing.JTextField();
        mc8 = new javax.swing.JTextField();
        mc9 = new javax.swing.JTextField();
        mc10 = new javax.swing.JTextField();
        mc11 = new javax.swing.JTextField();
        mc12 = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        rm7 = new javax.swing.JTextField();
        rm8 = new javax.swing.JTextField();
        rm9 = new javax.swing.JTextField();
        rm10 = new javax.swing.JTextField();
        rm11 = new javax.swing.JTextField();
        rm12 = new javax.swing.JTextField();
        jLabel38 = new javax.swing.JLabel();
        worker1 = new javax.swing.JTextField();
        jLabel39 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jLabel40 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        worktype = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        complaint1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(933, 750));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(15, 58, 232));

        jLabel1.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(52, 50, 40));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/admin.png"))); // NOI18N
        jLabel1.setText("Administrator");

        jButton1.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jButton1.setText("Pending Complaints");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jButton2.setText("Update Resources");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Logout-32.png"))); // NOI18N
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(177, 177, 177)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(90, 90, 90)
                .addComponent(jButton5)
                .addGap(57, 57, 57))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(325, 325, 325)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton1)
                        .addComponent(jButton2))
                    .addComponent(jButton5))
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(64, 177, 239));

        jLabel22.setFont(new java.awt.Font("Ubuntu", 1, 13)); // NOI18N
        jLabel22.setText("Complaint ID");

        jLabel23.setFont(new java.awt.Font("Ubuntu", 1, 13)); // NOI18N
        jLabel23.setText("Type of work");

        cid1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cid1ActionPerformed(evt);
            }
        });

        jLabel24.setFont(new java.awt.Font("Ubuntu", 1, 13)); // NOI18N
        jLabel24.setText("Mahcines(+/-)");

        jLabel25.setFont(new java.awt.Font("Ubuntu", 0, 13)); // NOI18N
        jLabel25.setText("Road Rollers");

        jLabel26.setFont(new java.awt.Font("Ubuntu", 0, 13)); // NOI18N
        jLabel26.setText("Road Marking Machines");

        jLabel27.setFont(new java.awt.Font("Ubuntu", 0, 13)); // NOI18N
        jLabel27.setText("Chips Spreader");

        jLabel28.setFont(new java.awt.Font("Ubuntu", 0, 13)); // NOI18N
        jLabel28.setText("Concrete Road Pavers");

        jLabel29.setFont(new java.awt.Font("Ubuntu", 0, 13)); // NOI18N
        jLabel29.setText("Asphalt Drum Mix Plant");

        jLabel30.setFont(new java.awt.Font("Ubuntu", 0, 13)); // NOI18N
        jLabel30.setText("JCB");

        mc7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mc7ActionPerformed(evt);
            }
        });

        mc10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mc10ActionPerformed(evt);
            }
        });

        mc12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mc12ActionPerformed(evt);
            }
        });

        jLabel31.setFont(new java.awt.Font("Ubuntu", 1, 13)); // NOI18N
        jLabel31.setText("Raw Materials(+/-)");

        jLabel32.setFont(new java.awt.Font("Ubuntu", 0, 13)); // NOI18N
        jLabel32.setText("Sand bags");

        jLabel33.setFont(new java.awt.Font("Ubuntu", 0, 13)); // NOI18N
        jLabel33.setText("Brick Trucks");

        jLabel34.setFont(new java.awt.Font("Ubuntu", 0, 13)); // NOI18N
        jLabel34.setText("Asphalt");

        jLabel35.setFont(new java.awt.Font("Ubuntu", 0, 13)); // NOI18N
        jLabel35.setText("Concrete");

        jLabel36.setFont(new java.awt.Font("Ubuntu", 0, 13)); // NOI18N
        jLabel36.setText("Cement bags");

        jLabel37.setFont(new java.awt.Font("Ubuntu", 0, 13)); // NOI18N
        jLabel37.setText("Limestone");

        jLabel38.setFont(new java.awt.Font("Ubuntu", 1, 13)); // NOI18N
        jLabel38.setText("Workers(+/-)");

        worker1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                worker1ActionPerformed(evt);
            }
        });

        jLabel39.setFont(new java.awt.Font("Ubuntu", 1, 13)); // NOI18N
        jLabel39.setText("Priotity");

        jButton4.setBackground(new java.awt.Color(242, 227, 148));
        jButton4.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/road-32.png"))); // NOI18N
        jButton4.setText("Allocate Work");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel40.setFont(new java.awt.Font("Ubuntu", 1, 13)); // NOI18N
        jLabel40.setText("Days required to complete the wrok");

        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });

        complaint1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Complaint ID", "Type of Work", "Priority"
            }
        ));
        complaint1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                complaint1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(complaint1);
        if (complaint1.getColumnModel().getColumnCount() > 0) {
            complaint1.getColumnModel().getColumn(0).setPreferredWidth(200);
            complaint1.getColumnModel().getColumn(1).setPreferredWidth(200);
            complaint1.getColumnModel().getColumn(2).setPreferredWidth(200);
        }

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel38)
                            .addComponent(jLabel24)
                            .addComponent(jLabel31))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel26)
                                    .addComponent(jLabel32)
                                    .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addComponent(rm8, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(30, 30, 30)
                                                .addComponent(jLabel35))
                                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(worker1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(mc8, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(rm7, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(mc7, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(30, 30, 30)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addComponent(jLabel34)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(rm9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(rm10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addComponent(jLabel27)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(mc10, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addComponent(jLabel28)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(mc9, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(worktype)))))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(cid1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(54, 54, 54)
                                        .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(47, 47, 47)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel29)
                            .addComponent(jLabel30)
                            .addComponent(jLabel36)
                            .addComponent(jLabel37)
                            .addComponent(jLabel39))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jTextField4)
                            .addComponent(mc11, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
                            .addComponent(rm11, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(mc12, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rm12, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(60, 60, 60))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel40)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(343, 343, 343)
                .addComponent(jButton4)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cid1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel39)
                    .addComponent(jLabel22)
                    .addComponent(worktype, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(jLabel25)
                    .addComponent(mc7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel28)
                    .addComponent(mc9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel29)
                    .addComponent(mc11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(mc8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel27)
                    .addComponent(mc10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel30)
                    .addComponent(mc12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel31)
                    .addComponent(jLabel32)
                    .addComponent(rm7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel34)
                    .addComponent(jLabel36)
                    .addComponent(rm9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rm11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel37)
                        .addComponent(rm10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(rm12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel33)
                        .addComponent(rm8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel35)))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel38)
                    .addComponent(worker1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel40)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addComponent(jButton4)
                .addContainerGap())
        );

        jLabel22.setVisible(false);
        jLabel23.setVisible(false);
        cid1.setVisible(false);
        jLabel39.setVisible(false);
        jButton4.setVisible(false);
        jLabel40.setVisible(false);
        jTextField2.setVisible(false);
        worktype.setVisible(false);
        jTextField4.setVisible(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cid1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cid1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cid1ActionPerformed

    private void mc7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mc7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mc7ActionPerformed

    private void mc10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mc10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mc10ActionPerformed

    private void mc12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mc12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mc12ActionPerformed

    private void worker1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_worker1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_worker1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        /*jLabel40.setVisible(true);
        jLabel22.setVisible(true);
        jLabel23.setVisible(true);
        jLabel39.setVisible(true);*/
        complaint1.setVisible(true);
       /* cid1.setVisible(true);
        jTextField2.setVisible(true);
        worktype.setVisible(true);
        jTextField4.setVisible(true);*/
        jButton4.setVisible(true);
        jButton4.setText("Allocate Work");
        Statement stmt=null;
        try {
            stmt=conn.createStatement();
        } catch (SQLException ex) {
            Logger.getLogger(administrator.class.getName()).log(Level.SEVERE, null, ex);
        }
        String sql="Select * from work where alloc=0";
        try {
            DefaultTableModel mo=(DefaultTableModel)complaint1.getModel();
             if (mo.getRowCount() > 0) {
              for (int i = mo.getRowCount() - 1; i > -1; i--) {
        mo.removeRow(i);
    }
}
            ResultSet rs=stmt.executeQuery(sql);
            while(rs.next())
            {
                int t=rs.getInt("type");
                int comid=rs.getInt("comid");
                int p=rs.getInt("priority");
                String type,priority;
                if(t==0)
                {
                   type=" Bridge Repair";
                }
                else if(t==1)
                    type="Pot Holes Repair";
                else if(t==2)
                    type="New road building";
                else if(t==3)
                    type="Speed breaker";
                else
                    type="FootPath building";
                if(p==0)
                    priority="Low";
                else if(p==1)
                    priority="Medium";
                else
                    priority="High";
                
                mo.addRow(new Object[]{comid,type,priority});
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(administrator.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
       
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
         DefaultTableModel mo=(DefaultTableModel)complaint1.getModel();
            String sql;
            ResultSet rs;
            Statement stmt=null;
        try {
            stmt=conn.createStatement();
        } catch (SQLException ex) {
            Logger.getLogger(Mayorreq.class.getName()).log(Level.SEVERE, null, ex);
        }
        jLabel40.setVisible(false);
        jLabel22.setVisible(false);
        jLabel23.setVisible(false);
        jLabel39.setVisible(false);
        cid1.setVisible(false);
        jTextField2.setVisible(false);
        worktype.setVisible(false);
        jTextField4.setVisible(false);
        jButton4.setVisible(true);
        jButton4.setText("Update Resources");
        mc7.setText("0");mc8.setText("0");mc9.setText("0");mc10.setText("0");mc11.setText("0");mc12.setText("0");
        rm7.setText("0");rm8.setText("0");rm9.setText("0");rm10.setText("0");rm11.setText("0");rm12.setText("0");
        worker1.setText("0");
        mo.setRowCount(0);mo.setColumnCount(0);
         mo.addColumn("Resource type");
             mo.addColumn("Total");
             mo.addColumn("Employed");
              mo.addColumn("Unemployed");
             sql="SELECT * from resources";
                try {
                    rs=stmt.executeQuery(sql);
                     while(rs.next())
                     {
                         //System.out.println(rs.getDate("start"));
                         mo.addRow(new Object[]{rs.getString("Type"),rs.getInt("Total"),rs.getInt("Employed"),rs.getInt("Unemployed")});
                     }
                } catch (SQLException ex) {
                    Logger.getLogger(Mayorreq.class.getName()).log(Level.SEVERE, null, ex);
                }
    }//GEN-LAST:event_jButton2ActionPerformed
    int coid;
    private void complaint1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_complaint1MouseClicked
        int row=complaint1.getSelectedRow();
        int col=complaint1.getSelectedColumn();
         System.out.println("HII"+row+" "+col);
        coid=(int)complaint1.getValueAt(row, 0);
         System.out.println("HII");
        cid1.setText(""+coid);
        worktype.setText((String)complaint1.getValueAt(row,1));
        jTextField4.setText((String)complaint1.getValueAt(row, 2));
       
        
        Statement stmt=null;
        try {
            stmt=conn.createStatement();
            int workers = 0,days = 0;
            int[] m=new int[7];int[] r=new int[7];
            String sql="Select * from work where comid="+coid;
            ResultSet rs=stmt.executeQuery(sql);
            while(rs.next())
            {
                for(int i=1;i<=6;i++)
                {
                    m[i]=rs.getInt("m"+i);
                    r[i]=rs.getInt("r"+i);
                }
                workers=rs.getInt("w");
                days=rs.getInt("days");
            }
            mc7.setText(""+m[1]);mc8.setText(""+m[2]);mc9.setText(""+m[3]);
            mc10.setText(""+m[4]);mc11.setText(""+m[5]);mc12.setText(""+m[6]);
            rm7.setText(""+r[1]);rm8.setText(""+r[2]);rm9.setText(""+r[3]);
            rm10.setText(""+r[4]);rm11.setText(""+r[5]);rm10.setText(""+r[6]);
            worker1.setText(""+workers);jTextField2.setText(""+days);
        } catch (SQLException ex) {
            Logger.getLogger(administrator.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_complaint1MouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        String btntext=jButton4.getText();
        if(btntext.equals("Allocate Work"))
        {
        int[] pos=new int[10000];
        int[] comid=new int[10000];
        int[] premc=new int[7];
        int[] preres=new int[7];
        int prework = 0;
         int[] totmc=new int[7];
        int[] totres=new int[7];
        int totwork = 0;
        
        Statement stmt=null;
        String sql="SELECT * from resources";
        try {
            stmt=conn.createStatement();
            ResultSet rs=stmt.executeQuery(sql);
            int count=1;
            while(rs.next())
            {
                if(count<=6)
                {
                premc[count]=rs.getInt("Unemployed");
                 totmc[count]=rs.getInt("Total");
                 //System.out.println("Total="+totmc[count]);
                }
                else if(count<=12)
                {
                    preres[count-6]=rs.getInt("Unemployed");
                     totres[count-6]=rs.getInt("Total");
                }
                else
                {
                    prework=rs.getInt("Unemployed");
                     totwork=rs.getInt("Total");
                }
                count++;
                 //System.out.println("HII"+count);
            }
            
            sql="Select * from work where alloc=0 ORDER BY priority desc";
            int[] mc=new int[7];
            int[] res=new int[7];
            int work = 0,i;
            rs=stmt.executeQuery(sql);
            // System.out.println("HII");
            int rowcount=0;
            while(rs.next())
            {
                int flag=1;
                pos[rowcount]=0;
                comid[rowcount]=rs.getInt("comid");
                for(i=1;i<=6;i++)
                {
                    mc[i]=rs.getInt("m"+i);
                    res[i]=rs.getInt("r"+i);
                    if(mc[i]>premc[i] || res[i]>preres[i])
                        flag=0;
                }
                // System.out.println("HII"+rowcount);
                work=rs.getInt("w");
                if(work>prework)
                    flag=0;
                if(flag==1)
                {
                    for(int j=1;j<=6;j++)
                    {
                        premc[j]-=mc[j];
                        preres[j]-=res[j];
                    }
                    prework-=work;
                    pos[rowcount]=1;
                }
                rowcount++;
                
            }
           
            for(i=0;i<rowcount;i++)
            {
                if(pos[i]==1)
                {
                    sql="Update complaints set status=2 where comid="+comid[i];
                    stmt.execute(sql);
                    
                    sql="Update work set alloc=1 where comid="+comid[i];
                    stmt.execute(sql);
                }
            }
            for(i=1;i<=6;i++)
            {
                sql="Update resources set Unemployed"+"="+premc[i]+" where Type="+"\"M"+i+"\"";
               
                stmt.execute(sql);
                
                 sql="Update resources set Employed"+"="+(totmc[i]-premc[i])+" where Type="+"\"M"+i+"\"";
               //   System.out.println(sql);
                 stmt.execute(sql);
                 sql="Update resources set Unemployed"+"="+preres[i]+" where Type="+"\"R"+i+"\"";
                 // System.out.println(sql);
                stmt.execute(sql);
                sql="Update resources set Employed"+"="+(totres[i]-preres[i])+" where Type="+"\"R"+i+"\"";
                // System.out.println(sql);
                 stmt.execute(sql);
                 sql="Update resources set Unemployed"+"="+(prework)+" where Type="+"\"W\"";
               //   System.out.println(sql);
                 stmt.execute(sql);
                 sql="Update resources set Employed"+"="+(totwork-prework)+" where Type="+"\"W\"";
               //   System.out.println(sql);
                 stmt.execute(sql);
            }
            String allocated = "";
            int countpos=0;
            for(i=0;i<rowcount;i++)
            {
                if(pos[i]==1)
                {
                    countpos++;
                    allocated+=","+(comid[i]);
                    
                }
            }
            if(countpos>0)
            JOptionPane.showMessageDialog(rootPane,"Work Has been allocated to complaint ids:-"+allocated);
            else
                JOptionPane.showMessageDialog(rootPane,"No work has been allocated");
        } catch (SQLException ex) {
            Logger.getLogger(Admin.class.getName()).log(Level.SEVERE, null, ex);
        }
        }
        else
        {
            String sql="Select * from resources";
            int[] premc=new int[7];
        int[] preres=new int[7];
        int prework = 0;
         int[] totmc=new int[7];
        int[] totres=new int[7];
        int totwork = 0;
        int[] comid=new int[10000];
        int[] notposs=new int[10000];
            Statement stmt=null;
            try {
                stmt=conn.createStatement();
                ResultSet rs=stmt.executeQuery(sql);
            int count=1;
            while(rs.next())
            {
                if(count<=6)
                {
                premc[count]=rs.getInt("Unemployed");
                 totmc[count]=rs.getInt("Total");
                }
                else if(count<=12)
                {
                    preres[count-6]=rs.getInt("Unemployed");
                     totres[count-6]=rs.getInt("Total");
                }
                else
                {
                    prework=rs.getInt("Unemployed");
                     totwork=rs.getInt("Total");
                }
                count++;
                 //System.out.println("HII"+count);
            }
            
            int m7=Integer.parseInt(mc7.getText());int m8=Integer.parseInt(mc8.getText());int m9=Integer.parseInt(mc9.getText());
           int m10=Integer.parseInt(mc10.getText());int m11=Integer.parseInt(mc11.getText());
           int m12=Integer.parseInt(mc12.getText());
           int r7=Integer.parseInt(rm7.getText());int r8=Integer.parseInt(rm8.getText());
           int r9=Integer.parseInt(rm9.getText());int r10=Integer.parseInt(rm10.getText());
           int r11=Integer.parseInt(rm11.getText());int r12=Integer.parseInt(rm12.getText());
           int worker=Integer.parseInt(worker1.getText());
           /*premc[1]+=m7;premc[2]+=m8;premc[3]+=m9;premc[4]+=m10;premc[5]+=m11;premc[6]+=m12;
           preres[1]+=r7;preres[2]+=r8;preres[3]+=r9;preres[4]+=r10;preres[5]+=r11;preres[6]+=r12;
           prework+=worker;*/
            totmc[1]+=m7;totmc[2]+=m8;totmc[3]+=m9;totmc[4]+=m10;totmc[5]+=m11;totmc[6]+=m12;
           totres[1]+=r7;totres[2]+=r8;totres[3]+=r9;totres[4]+=r10;totres[5]+=r11;totres[6]+=r12;
           totwork+=worker;
           int i;
           for(i=1;i<=6;i++)
           {
               premc[i]=totmc[i];
               preres[i]=totres[i];
           }
           prework=totwork;
           System.out.println(premc[1]+"HIIIITotal "+totmc[1]);
           sql="Select * from work where alloc=1 and end is null order by priority";
            rs=stmt.executeQuery(sql);
            int rowcount=0;
            while(rs.next())
            {
                int flag=1;
                comid[rowcount]=rs.getInt("comid");
                System.out.println(comid[rowcount]+"FKFK");
                int[] m=new int[7];int[] r=new int[7];int w;
                w=rs.getInt("w");
               
                if(w>prework)
                    flag=0;
                for(i=1;i<=6;i++)
                {
                    m[i]=rs.getInt("m"+i);
                    r[i]=rs.getInt("r"+i);
                    if(m[i]>premc[i] || r[i]>preres[i])
                        flag=0;
                }
                System.out.println(m[1]+ "BYEE "+premc[1]);
                if(flag==0)
                {
                    //System.out.println("HUURR");
                    notposs[rowcount]=1;
                   
                }
                else
                {
                    notposs[rowcount]=0;
                    for(i=1;i<=6;i++)
                    {
                        premc[i]-=m[i];
                        preres[i]-=r[i];
                    }
                    prework-=w;
                }
                rowcount++;
            }
            for(i=0;i<rowcount;i++)
            {
                if(notposs[i]==1)
                {
                    sql="Update work set alloc=0,end=NULL,start=NULL where comid="+comid[i];
                    stmt.execute(sql);
                    sql="Update complaints set status=1 where comid="+comid[i];
                    stmt.execute(sql);
                    
                }
            }
           
            for(i=1;i<=6;i++)
            {
                if(totmc[i]>=0)
                {
                sql="Update resources set Total="+totmc[i]+" where Type="+"\"M"+i+"\"";
               // System.out.println(sql);
                stmt.execute(sql);
                }
                if(totres[i]>=0)
                {
                sql="Update resources set Total="+totres[i]+" where Type="+"\"R"+i+"\"";
                stmt.execute(sql);
                }
                if(premc[i]>=0)
                {
                sql="Update resources set Unemployed="+premc[i]+" where Type="+"\"M"+i+"\"";
                stmt.execute(sql);
                }
                if(preres[i]>=0)
                {
                sql="Update resources set Unemployed="+preres[i]+" where Type="+"\"R"+i+"\"";
                stmt.execute(sql);
                }
                if(totmc[i]-premc[i]>=0)
                {
                sql="Update resources set Employed="+(totmc[i]-premc[i])+" where Type="+"\"M"+i+"\"";
                stmt.execute(sql);
                }
                if(totres[i]-preres[i]>=0)
                {
                sql="Update resources set Employed="+(totres[i]-preres[i])+" where Type="+"\"R"+i+"\"";
                stmt.execute(sql);
                }
            }
            if(totwork>=0)
            {
            sql="Update resources set Total="+totwork+" where Type="+'\"'+"W"+'\"';
            stmt.execute(sql);
            }
            if(prework>=0)
            {
            sql="Update resources set Unemployed="+prework+" where Type="+'\"'+"W"+'\"';
            stmt.execute(sql);
            }
            if(totwork-prework>=0)
            {
            sql="Update resources set Employed="+(totwork-prework)+" where Type="+'\"'+"W"+'\"';
            stmt.execute(sql);
            }
            String realloc="";
            count=0;
            for(i=0;i<rowcount;i++)
            {
                
                if(notposs[i]==1)
                {
                    count++;
                    System.out.println("GKKG"+comid[i]);
                    realloc=realloc+','+(comid[i]);
                }
            }
            if(count>0)
            {
                JOptionPane.showMessageDialog(rootPane, "Works deallocated are"+realloc);
                JOptionPane.showMessageDialog(rootPane,"New work may be allocated.Please Click on Allocate Work");
            }
            else
            {
                JOptionPane.showMessageDialog(rootPane,"New work may be allocated.Please Click on Allocate Work");
            }
            } catch (SQLException ex) {
                Logger.getLogger(Admin.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new Login().setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cid1;
    private javax.swing.JTable complaint1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField mc10;
    private javax.swing.JTextField mc11;
    private javax.swing.JTextField mc12;
    private javax.swing.JTextField mc7;
    private javax.swing.JTextField mc8;
    private javax.swing.JTextField mc9;
    private javax.swing.JTextField rm10;
    private javax.swing.JTextField rm11;
    private javax.swing.JTextField rm12;
    private javax.swing.JTextField rm7;
    private javax.swing.JTextField rm8;
    private javax.swing.JTextField rm9;
    private javax.swing.JTextField worker1;
    private javax.swing.JTextField worktype;
    // End of variables declaration//GEN-END:variables
}
