
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author sayan
 */
public class update extends javax.swing.JFrame {

    /**
     * Creates new form update
     */
    Login l;
   public int id;
    Connection conn=null;
    public update() {
        initComponents();
       l=new Login();
        try {
            Class.forName("com.mysql.jdbc.Driver");
            String user="root";
            String pass="sayan1994";
            String DB_URL = "jdbc:mysql://"+l.IP_ADD+"/rrts";
            conn = DriverManager.getConnection(DB_URL,user,pass);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(entercom.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(entercom.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        complaint = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(15, 58, 232));

        jLabel1.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(52, 50, 40));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/seo-97-48.png"))); // NOI18N
        jLabel1.setText("Update Complaint Status");

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/home-32.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(76, 76, 76)
                .addComponent(jButton1)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(64, 177, 239));

        complaint.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Complaint ID", "Road ID", "Current Status"
            }
        ));
        complaint.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                complaintMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(complaint);

        jButton2.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CheckCompleted-48.png"))); // NOI18N
        jButton2.setText("Update");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 614, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(197, 197, 197)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void showComplaints()
    {
         if(id==0)
        {
            JTextField locality = new JTextField();
        
        Object[] message = {
            "Locality ID:", locality
            
        };
        while(true){
        int option = JOptionPane.showConfirmDialog(null, message, "Locality", JOptionPane.OK_CANCEL_OPTION);
        if (option == JOptionPane.OK_OPTION) {
            id=(Integer.parseInt(locality.getText()));
            if(id<20 && id>0)
            {
               // this.dispose();
                break;
            }
            else {
                JOptionPane.showMessageDialog (null, "Incorrect Locality Id", "Locality", JOptionPane.ERROR_MESSAGE);

            }
        } 
        } 
        }
        
        Statement stmt=null;
        try {
            stmt=conn.createStatement();
        } catch (SQLException ex) {
            Logger.getLogger(update.class.getName()).log(Level.SEVERE, null, ex);
        }
        String sql="SELECT * from complaints where LocId="+id;
        ResultSet rs;
        try {
            rs = stmt.executeQuery(sql);
             DefaultTableModel mo=(DefaultTableModel)complaint.getModel();
                if (mo.getRowCount() > 0) {
                      for (int i = mo.getRowCount() - 1; i > -1; i--) {
                         mo.removeRow(i);
                     }
                }
             while(rs.next())
            {
                int coid=rs.getInt("comid");
                int st=rs.getInt("status");
                int rid=rs.getInt("RoadID");
               String status;
                if(st==1)
                {
                    status="Reviewed";
                }
                else if(st==0)
                {
                    status="Pending";
                }
                else if(st==2)
                {
                    status="Allocated";
                }
                else
                    status="Completed";
          
               
                
                mo.addRow(new Object[]{coid,rid,status});
                
            
            
             }
        } catch (SQLException ex) {
            Logger.getLogger(update.class.getName()).log(Level.SEVERE, null, ex);
        }
    }    int tstatus,tcid,row;
    private void complaintMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_complaintMouseClicked
        // TODO add your handling code here:
         row=complaint.getSelectedRow();
        int col=complaint.getSelectedColumn();
        tcid=(int)complaint.getValueAt(row,0);
        String status=(String)complaint.getValueAt(row,2);
        if(status.equals("Pending"))
            tstatus=0;
        else if(status.equals("Allocated"))
            tstatus=2;
         else if(status.equals("Reviewed"))
            tstatus=1;
        else
             tstatus=3;
        
        
    }//GEN-LAST:event_complaintMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        if(tstatus!=2)
        {
            JOptionPane.showMessageDialog(complaint,"Complaint has not been allocated still or has been completed");
            return;
        }
        String sql="Update complaints set status=3 where comid="+tcid;
        
        Statement stmt=null;
        Date currentdate = new Date();
        java.sql.Date sqlDate = new java.sql.Date(currentdate.getTime());
        System.out.println(currentdate+"\n"+sqlDate);
       try {
           stmt=conn.createStatement();
            stmt.execute(sql);
            
            //sql="Update work set end="+sqlDate+"where comid="+tcid;
           // stmt.execute(sql);
            sql="Update work set end="+" NOW()"+" where comid="+tcid;
            System.out.println(sql);
            stmt.execute(sql);
            DefaultTableModel mo=(DefaultTableModel)complaint.getModel();
            mo.setValueAt(new String("Completed"), row, 2);
            sql="Select * from work where comid="+tcid;
            ResultSet rs=stmt.executeQuery(sql);
            
            int[] m = new int[200];
            int[] total = new int[200];
            int[] unemployed=new int[200];;
            int[] employed=new int[200];;
            int worker;
            int i=1;
            while(rs.next())
            {
                for(i=1;i<=6;i++)
                {
                m[i]=rs.getInt("m"+i);
                System.out.println(""+i+" "+m[i]);
                }
                worker=rs.getInt("w");
                
            }
            sql="Select * from resources";
            String sql1;
            rs=stmt.executeQuery(sql);
            
            int count=1;
            while(rs.next())
            {
                
                
                unemployed[count]=rs.getInt("Unemployed");
                employed[count]=rs.getInt("Employed");
                System.out.println(" "+count+" "+unemployed[count]+ " " + employed[count]);
                count++;
                
            }
            for(count=1;count<=13;count++)
            {
                if(count<=6)
                {
                    
                    unemployed[count]+=m[count];
                    employed[count]-=m[count];
                   
                   
                   
                    sql1="Update resources set Unemployed="+unemployed[count]+" where Type= "+"\""+"M"+count+"\"";
                     System.out.println(sql1);
                    stmt.execute(sql1);
                    sql1="Update resources set Employed="+employed[count]+" where Type= "+"\""+"M"+count+"\"";
                     System.out.println(sql1);
                    stmt.execute(sql1);
                }
                else if(count==13)
                {
                    
                    unemployed[count]+=m[count];
                    employed[count]-=m[count];
                    
                    
                    sql1="Update resources set Unemployed="+unemployed[count]+" where Type=\"W\"";
                     System.out.println(sql1);
                    stmt.execute(sql1);
                     System.out.println(sql1);
                    sql1="Update resources set Employed="+employed[count]+" where Type=\"W\"";
                    stmt.execute(sql1);
                }
            }
            
            JOptionPane.showMessageDialog(complaint, "Updated");
           
       } catch (SQLException ex) {
           Logger.getLogger(update.class.getName()).log(Level.SEVERE, null, ex);
       }
      
       
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new Supervisor().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new update().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable complaint;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
